# Book Settings
title: "AI Search Algorithms for Smart Mobility"
logo: images/book.png
author: Alaa Khamis and Yinan Wang

#Jupyter Settings
execute:
  execute_notebooks: "auto"
  timeout: 140

# HTML Settings
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    bibtex_reference_style: label
    html_theme: sphinx_book_theme
  extra_extensions:
  - sphinx_inline_tabs
bibtex_bibfiles:
- references.bib
html:
  extra_footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">
    <img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a>
    <span>This work is licensed under a 
    <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.</span>
  home_page_in_navbar: False
  
#Interactive Settings
repository:
  url:  https://github.com/SmartMobilityAlgorithms/book
  branch: release/updated_content
launch_buttons: 
  colab_url: "https://colab.research.google.com"