dependencies:
- python=3.8
- pip:
  - smart_mobility_utilities>=0.0.6
  - overpass>=0.7
  - folium>=0.12.1
- Cython>=0.29.24
- numpy>=1.20.3
- geoplot>=0.4.3
- plotly>=5.2.1
- osmnx>=1.1.1
- networkx>=2.6.2
- pandas>=1.3.2
- scipy>=1.7.1
- scikit-learn>=0.24.2
- ipyleaflet>=0.14.0
- shapely>=1.7.1
- jupyter-book>=0.11.2
- matplotlib>=3.4.3
- numpy>=1.20.3
- geopandas>=0.9.0
- contextily>=1.1.0
- tqdm>=4.62.1